### ISSUE TITLE
Number format.

### ISSUE THREAD

**Issue by sheijmans** [spotify/puppetexplorer#21]
At work we use the Dutch number format on Windows PC's.
Numbers on the dashboard page are formatted this way;
Nodes: 369,00
Resources: 150.2
Avg resources/node: 407,24
Resource duplication %: 96,82

instead of the correct presentation with English number format;
Nodes: 369
Resources: 150,271
Avg resources/node: 407.2
Resource duplication %: 96.8

Is this fixable without switching to English number format in Windows?

**Comment by dalen** [comment]
Sorry for a really late reply. But I think the language settings are possible to set in the browser preferences instead of doing it globally in the OS. Generally it is good for apps to respect localization settings and number formats, but I suppose it can become messy in some cases like this.

**Comment by sheijmans** [comment]
I've changed the language settings in IE to first en-US en second nl-NL but this didn't help with the number formatting.

**Comment by sheijmans** [comment]
Hmnm, doing the same with portable Chrome does work, will stick to that with for this.
