### ISSUE TITLE
not working with firefox

### ISSUE THREAD

**Issue by Poil** [spotify/puppetexplorer#23]
Hi,,

Last version is no more working with firefox :
```
"TypeError: Error.captureStackTrace is not a function"
```

**Comment by Poil** [comment]
If you check other nodejs module you have this code

```
  if (Error.captureStackTrace) {
    Error.captureStackTrace(this, stackStartFunction);
  }
  else {
    // non v8 browsers so we can have a stacktrace
    var err = new Error();
    if (err.stack) {
      var out = err.stack;

      // try to strip useless frames
      var fn_name = stackStartFunction.name;
      var idx = out.indexOf('\n' + fn_name);
      if (idx >= 0) {
        // once we have located the function frame
        // we need to strip out everything before it (and its line)
        var next_line = out.indexOf('\n', idx + 1);
        out = out.substring(next_line + 1);
      }

      this.stack = out;
    }
  }
```

It seem you don't have it in node_modules/node-puppetdbquery/node_modules/ast-types/node_modules/depd/index.js and node_modules/node-puppetdbquery/node_modules/ast-types/node_modules/depd/lib/compat/index.js

**Comment by dje4om** [comment]
Hi,

1.3.1 tag release works fine with Firefox (current version), but there is the same error with IE9.

**Comment by dalen** [comment]
I've been a bit busy the last few days and now I broke my wrist :( so will
see when I can take a closer look at this. Likely some dependency needs
updating.

**Comment by dalen** [comment]
In 1.4.0 I've updated the dependencies to later versions and fixed this error (was in a dependency of a dependency of a dependency that required a V8 specific javascript feature...).
