### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by n1tr0g** [spotify/puppetexplorer#25]
Hey,

would be really great if you add the Change Log for 1.4 ... tnx

p.s. - great work with puppetexplorer

**Comment by dalen** [comment]
Thanks, I'm looking into some changelog generation scripts. https://github.com/skywinder/github-changelog-generator seems promising, just need to work a bit on actually using the GH issues features a bit more.

**Comment by dalen** [comment]
I've updated the release info now to list the improvements: https://github.com/spotify/puppetexplorer/releases/tag/1.4.0
