### ISSUE TITLE
Question: puppetdb 3 support?

### ISSUE THREAD

**Issue by wooziethe** [spotify/puppetexplorer#31]
Hello,

Are you planning to support puppet 4.2 / puppetdb 3.0? When this might happen?

Thank you,
Alex

**Comment by mitch-hulscher** [comment]
I am also interested in this. Would love to move to puppetdb 3.0 and use puppetexplorer.

**Comment by alexanderdavidsen** [comment]
I would love to see PuppetDB 3.0 support!

**Comment by Dantonrrc** [comment]
Same here!

**Comment by AxisNL** [comment]
Same here! Got anything planned?

**Comment by dalen** [comment]
Hi, sorry for the a bit late reply. I've been away a bit on vacation until today. I've setup a PuppetDB 3.0 dev environment already, but haven't had much time lately to work on the support. I hope to have something ready for release the coming week (before 21 august).

**Comment by tux-o-matic** [comment]
Tried a mapping of AJAX requests to the PuppetDB endpoints. Some are pretty straightforward like:
* /v4/version to /pdb/meta/v1/version
* /v4/metrics/mbean/com.puppetlabs.puppetdb.query.population to /metrics/v1/mbeans/puppetlabs.puppetdb.query.population

It gets more complicated for endpoints which have not only moved but also changes or dropped some parameters.
* /pdb/query/v4/event-counts no longer as the same parameters and summer-by is now summerize_by and same goes to its value containing-class which is now containing_class.
* /pdb/query/v4/reports doesn't seem to accept the same filter as a simple mapping of the path leads to several MB being downloaded.

**Comment by dalen** [comment]
The names of all parameters that used to contain dashes are now separated by underscores. Also puppetdb now also consistently uses certname, previously it was name in some places and certname in some places.

Both those changes should simplify the code a bit.

**Comment by tux-o-matic** [comment]
Do you have an ETA for support of the new version or you'd like some community help for this?

**Comment by dalen** [comment]
Releasing 2.0.0 now. It supports puppetdb 3.x (but not 2.x). Doesn't use any of the new features yet though, will add that in coming releases (but I'm away traveling next week, so likely sometime after that :) )

**Comment by tux-o-matic** [comment]
Even when upgrade Puppet Explorer to the latest version on GIT, many things are still broken compared to my previous attempt of just remapping things to their new endpoints.
* The "nodes" tab gets 404 on event-counts and then other requests just seem to pull MB till Chrome crashes.
* Events isn't working, just pulling random event data.
* Facts are broken and just pull values for every facts.
* Still get messages about summerize_by even though it's using the new spelling in the request.
