### ISSUE TITLE
Problems with latest version and puppetdb 3.0

### ISSUE THREAD

**Issue by alexanderdavidsen** [spotify/puppetexplorer#33]
Hi,

I'm trying to get the latest git version of puppetexplorer working with puppetdb3.0.

I'm proxy all request to puppetdb via apache, as recommended in the README. My proxypass config looks like this:

    ProxyPass /api http://localhost:8080/
    ProxyPassReverse /api http://localhost:8080/

and config.js:

PUPPETDB_SERVERS = [
  ['production', '/api'],
];

When trying to access Puppetexplorer via http i get the following error:

<p>The requested URL /pdb/dashboard/index.html was not found on this server.</p>

It looks like it's trying to pull index.html via the puppetdb api?
I'm not getting any info from puppetdb in the dashboard either.

Trying to access /api with curl gives me a 302:
 curl -X GET http://localhost/api/pdb/meta/v1/version
::1 - - [20/Aug/2015:08:45:54 +0200] "GET /api/pdb/meta/v1/version HTTP/1.1" 302 - "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"

Any ideas what I'm doing wrong? 

Regards,
Alexander

**Comment by alexanderdavidsen** [comment]
Got it working;

ProxyPass /api http://localhost:8080
ProxyPassReverse /api http://localhost:8080

Seems to do the trick.

**Comment by dalen** [comment]
yeah, apache doesn't like trailing slashes there. Anyway, releasing 2.0.0 now with the puppetdb 3.x support. Doesn't use any of the new features of puppetdb 3.x yet, just a compatibility release to work with it.

**Comment by lightoze** [comment]
I'm getting the following error now:
```
'report-timestamp' is not a queryable object for nodes, known queryable objects are ["catalog_environment","catalog_timestamp","certname","deactivated","expired","facts_environment","facts_timestamp","report_environment","report_timestamp"]
```

**Comment by alexanderdavidsen** [comment]
Change report-timestamp to report_timestamp. This goes for a few other variables in config.js too.

**Comment by lightoze** [comment]
So it's because puppet forge module is not updated yet. Thanks for pointing this out!

**Comment by dalen** [comment]
Yup, I'll release a new forge module today with the new default queries. Sorry about the confusion.

**Comment by ocontant** [comment]
Hi Dalen, puppetforge only have version 1.1.1 available.  Do you intend to make 2.0.0 available?
