### ISSUE TITLE
Unable to look for latest catalog with errors

### ISSUE THREAD

**Issue by roidelapluie** [spotify/puppetexplorer#43]
I try to get the list of node who have failures but I get an error because of the ? in latest_report:

![latest](https://cloud.githubusercontent.com/assets/291750/11838260/210ab08a-a3e6-11e5-85e2-b1b3cce133ff.png)

**Comment by roidelapluie** [comment]
```
#event.status = failure and #event."latest_report?" = true
```
works but doesn't do what I want

**Comment by roidelapluie** [comment]
Good answer is

```
#event { status = failure and "latest_report?" = true }
```

**Comment by dalen** [comment]
On puppetdb 3.2 you can use `#node.latest_report_status=failure`.
