### ISSUE TITLE
Resources not found

### ISSUE THREAD

**Issue by davinerd** [spotify/puppetexplorer#56]
Hello,
I'm using puppetdb 4.1 on Ubuntu 16.04. When I open the dashboard I receive:

```
GET https://my_ip_address/api/metrics/v1/mbeans/puppetlabs.puppetdb.query.population:type=default,name=pct-resource-dupes 404 (Not Found)

Error: Could not fetch metric pct-resource-dupes from PuppetDB
```

Here's my `25-localhost` ProxyPass section:

```
ProxyPass /api http://localhost:8080
ProxyPassReverse /api http://localhost:8080

ProxyPass /api/pdb/query http://localhost:8080/pdb/query
ProxyPassReverse /api/pdb/query http://localhost:8080/pdb/query
ProxyPass /api/pdb/meta http://localhost:8080/pdb/meta
ProxyPassReverse /api/pdb/meta http://localhost:8080/pdb/meta
ProxyPass /api/metrics http://localhost:8080/metrics
ProxyPassReverse /api/metrics http://localhost:8080/metrics
```
It seems like that URL does not exist anymore. 
Am I missing something?

Thanks

**Comment by garethr** [comment]
I just hit this as well.

hitting `/metrics/v1/mbeans` shows the following endpoints. Note that the above version has `query.population` where as the following just has `population`.

```
puppetlabs.puppetdb.population:name=avg-resources-per-node: "/mbeans/puppetlabs.puppetdb.population%3Aname%3Davg-resources-per-node",
puppetlabs.puppetdb.population:name=num-active-nodes: "/mbeans/puppetlabs.puppetdb.population%3Aname%3Dnum-active-nodes",
puppetlabs.puppetdb.population:name=num-inactive-nodes: "/mbeans/puppetlabs.puppetdb.population%3Aname%3Dnum-inactive-nodes",
puppetlabs.puppetdb.population:name=num-nodes: "/mbeans/puppetlabs.puppetdb.population%3Aname%3Dnum-nodes",
puppetlabs.puppetdb.population:name=num-resources: "/mbeans/puppetlabs.puppetdb.population%3Aname%3Dnum-resources",
puppetlabs.puppetdb.population:name=pct-resource-dupes: "/mbeans/puppetlabs.puppetdb.population%3Aname%3Dpct-resource-dupes",
```

**Comment by garethr** [comment]
This is documented here https://docs.puppet.com/puppetdb/4.1/api/metrics/v1/changes-from-puppetdb-v3.html#population-metrics

It's a change between the v3 and v4 APIs.

The code seemingly already accounts for this
https://github.com/spotify/puppetexplorer/blob/bdb6c4071962a817e8a356ebf5e704ad03e77087/app/controllers/dashboard/dashboard.coffee#L28

Hitting `/pdb/meta/v1/version` returns:

```
{
  "version" : "4.1.0"
}
```

I'm using the latest released 2.0.0 version of puppetexplorer. Which does not include the above change.

If you're brave you can patch the compiled js source code. Find the following:

```javascript
bean="puppetlabs.puppetdb.query.population"),this.$scope[scopeName]=void 0,this.PuppetDB.getBean(bean+":type=default,name="+name)
```

And change to this:

```javascript
bean="puppetlabs.puppetdb.population"),this.$scope[scopeName]=void 0,this.PuppetDB.getBean(bean+":name="+name)
```

**Comment by garethr** [comment]
If you're seemingly as crazy as me, and think "I know, I'll use sed to fix this" then here you go.

```
sed -i -e 's/puppetlabs\.puppetdb\.query\.population/puppetlabs\.puppetdb\.population/g' -e 's/type=default,//g' app.js
```

The ideal fix is for there to be a new release of puppetexplorer under the github releases link.

**Comment by davinerd** [comment]
Sure I am!

I'll try to fix later and let you know, thanks!

**Comment by davinerd** [comment]
Sorry for the late reply, it worked like a charm.

Thanks

**Comment by wortmanb** [comment]
I've been fighting this for weeks or months and just now found this. My fault for not looking at closed issues. ;-)

Thanks for sharing.
